package com.pdfcreator.creator;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

public class CreatorClass {

	private static Font TIME_ROMAN = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
	private static Font TIME_ROMAN_SMALL = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

	public static Document createPDF(String file, String mail[], String name[], String password[], int Entry) {

		Document document = null;

		try {
			document = new Document();
			PdfWriter.getInstance(document, new FileOutputStream(file));
			document.open();

			addMetaData(document);

			addTitlePage(document);

			createTable(document,mail, name, password, Entry);

			document.close();

		} catch (FileNotFoundException e) {

			e.printStackTrace();
		} catch (DocumentException e) {
			e.printStackTrace();
		}
		return document;

	}

	private static void addMetaData(Document document) {
		document.addTitle("sample report generated by KK");
		document.addSubject("sample report");
		document.addAuthor("Karthikeyan");
		document.addCreator("Karthikeyan");
	}

	private static void addTitlePage(Document document) throws DocumentException {

		Paragraph preface = new Paragraph();
		creteEmptyLine(preface, 1);
		preface.add(new Paragraph("Details", TIME_ROMAN));

		creteEmptyLine(preface, 1);
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MM/dd/yyyy");
		preface.add(new Paragraph("Report created on " + simpleDateFormat.format(new Date()), TIME_ROMAN_SMALL));
		document.add(preface);

	}
	private static void creteEmptyLine(Paragraph paragraph, int number) {
		for (int i = 0; i < number; i++) {
			paragraph.add(new Paragraph(" "));
		}
	}

	private static void createTable(Document document, String mail[], String name[] , String password[], int Entry) throws DocumentException {
		System.out.println("Creating table...");
		Paragraph paragraph = new Paragraph();
		creteEmptyLine(paragraph, 3);
		document.add(paragraph);
		PdfPTable table = new PdfPTable(3);

		PdfPCell cell1 = new PdfPCell(new Paragraph("username"));
		PdfPCell cell2 = new PdfPCell(new Paragraph("password"));
		PdfPCell cell3 = new PdfPCell(new Paragraph("Mail"));
		table.addCell(cell1);
		table.addCell(cell2);
		table.addCell(cell3);
		System.out.println("adding entries... =-");
		for(int ctr=0;ctr<Entry;ctr++) {
//		PdfPCell cell4 = ;
//		PdfPCell cell5 = new PdfPCell(new Paragraph(password));
//		PdfPCell cell6 = new PdfPCell(new Paragraph(mail));
		//System.out.println( name[ctr] + mail[ctr] + password[ctr]);
			
		table.addCell(new PdfPCell(new Paragraph(name[ctr])));
		table.addCell(new PdfPCell(new Paragraph(mail[ctr])));
		table.addCell(new PdfPCell(new Paragraph(password[ctr])));
		}

		// Add cells in table
		
		document.add(table);
		System.out.println("Process end...");
	}

}
